version: "3"

services:
  web:
    build: .
    ports:
      - "3005:80"
    volumes:
      - "./:/app"
    command: "php -S 0.0.0.0:80 -t public"

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"
